DATASET:
  NAME: "voc2007"
  ROOT: "/data1/yq/008_clip_int/DualCoOp/datasets/VOCdevkit/VOC2007"
  VAL_SPLIT: "test"
  TEST_SPLIT: "test"
  TRAIN_SPLIT: "trainval"
  ZS_TRAIN: ""
  ZS_TEST: ""
  ZS_TEST_UNSEEN: ""
